"""Initial revision

Revision ID: 0cefb8c00636
Revises: 8236914ec650
Create Date: 2025-03-05 15:10:44.511309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cefb8c00636'
down_revision: Union[str, None] = '8236914ec650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Question_group_id_fkey', 'Question', type_='foreignkey')
    op.drop_column('Question', 'group_id')
    op.drop_constraint('Question_group_user_id_fkey', 'Question_group', type_='foreignkey')
    op.drop_column('Question_group', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question_group', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Question_group_user_id_fkey', 'Question_group', 'User', ['user_id'], ['id'])
    op.add_column('Question', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Question_group_id_fkey', 'Question', 'Question_group', ['group_id'], ['id'])
    # ### end Alembic commands ###
