"""Initial revision

Revision ID: 1ecd5cc5fce5
Revises: 0cefb8c00636
Create Date: 2025-03-05 16:45:19.985477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecd5cc5fce5'
down_revision: Union[str, None] = '0cefb8c00636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('correct_answr', sa.String(), nullable=False))
    op.drop_column('Question', 'r_answr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Question', sa.Column('r_answr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Question', 'correct_answr')
    # ### end Alembic commands ###
