"""Initial revision

Revision ID: de9220d58143
Revises: 1de8d337550b
Create Date: 2025-03-05 12:41:55.115200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de9220d58143'
down_revision: Union[str, None] = '1de8d337550b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Question', ['id'])
    op.create_unique_constraint(None, 'Question_group', ['id'])
    op.add_column('User', sa.Column('username', sa.String(), nullable=True))
    op.add_column('User', sa.Column('email', sa.String(), nullable=False))
    op.add_column('User', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_constraint('User_user_name_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['username'])
    op.create_unique_constraint(None, 'User', ['email'])
    op.create_unique_constraint(None, 'User', ['id'])
    op.drop_column('User', 'user_name')
    op.drop_column('User', '_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('User', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_user_name_key', 'User', ['user_name'])
    op.drop_column('User', 'hashed_password')
    op.drop_column('User', 'email')
    op.drop_column('User', 'username')
    op.drop_constraint(None, 'Question_group', type_='unique')
    op.drop_constraint(None, 'Question', type_='unique')
    # ### end Alembic commands ###
